import os
from fpdf import FPDF

class PDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.set_text_color(33, 37, 41)
        self.cell(0, 10, 'Agentic Linguistics Analyzer (PMDD)', 0, 1, 'C')
        self.set_font('Helvetica', 'I', 11)
        self.set_text_color(100, 100, 100)
        self.cell(0, 8, 'Design & Structure of the Final Scientific Analysis Report', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        self.set_font('Helvetica', 'B', 12)
        self.set_fill_color(220, 230, 241)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, f'  {title}', 0, 1, 'L', 1)
        self.ln(4)

    def chapter_body(self, body):
        self.set_font('Helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 6, body)
        self.ln(6)

def generate_pdf():
    pdf = PDF()
    pdf.add_page()

    # 1. Introduction and Overview
    pdf.chapter_title("1. Report Purpose & Scientific Rigor")
    body1 = (
        "This document outlines the structure of the final analysis report generated by the PMDD "
        "(Pragmatic Meaning Drift Detector) application. Designed strictly for the academic and scientific research "
        "community, this report acts as a verifiable scholarly artifact.\n\n"
        "By utilizing a 5-Agent architecture with a Reflective Brain (OpenAI API powered self-correction) and Episodic "
        "Memory (learning from previous analyses), the system dynamically adapts to the corpus. Instead of strict NLP "
        "rules, it employs established Linguistic Theories to analyze large corpora, providing robust conclusions."
    )
    pdf.chapter_body(body1)

    # 2. Structure of the Report
    pdf.chapter_title("2. Structure of the Final Analysis Report")
    body2 = (
        "The final report will be formatted into the following standardized sections:\n"
        "1. Executive Summary: High-level overview of meaning drift scores and core semantic shifts.\n"
        "2. Methodological & Theoretical Framework: Explicit statement of linguistic theories applied (e.g., Searle, Grice, Halliday) to ensure reproducibility.\n"
        "3. Quantitative Landscape (Agent 4): Statistical distributions, TTR, and keyness.\n"
        "4. Qualitative Pragmatic & Semantic Analysis (Agents 2 & 3): In-depth review of speech acts, maxims, and semantic fields.\n"
        "5. Interpretative Synthesis (Agent 5): How the qualitative and quantitative data converge to prove the linguistic drift.\n"
        "6. Evidence Appendix: Raw data mapping with segment citations."
    )
    pdf.chapter_body(body2)

    # 3. Quantitative and Qualitative Evidence Integration
    pdf.chapter_title("3. Presentation of Linguistic Evidence (30/70 Ratio)")
    body3 = (
        "The report balances scientific metrics with deep contextual analysis, maintaining a strict evidence ratio:\n\n"
        "Quantitative Evidence (30%):\n"
        "- Statistical Tables: Word frequencies, Collocation strength (Mutual Information), and Log-Likelihood scores.\n"
        "- Semantic Drift Charts: Numerical representation of shifts in conceptual clustering.\n"
        "- Example presentation: 'Keyword X showed an MI score of 6.5 in Period A, dropping to 2.1 in Period B.'\n\n"
        "Qualitative Evidence (70%):\n"
        "- Verbatim Corpus Extracts: Exact sentences pulled from the text (referenced by Segment ID) to illustrate the statistics.\n"
        "- Contextual Interpretation: Explaining *why* the shift occurred using pragmatic maxims.\n"
        "- Example presentation: [Segment #1042]: 'We must fight this policy.' -> Analyzed as an explicit Directive speech act, demonstrating the statistical shift toward authoritarian register."
    )
    pdf.chapter_body(body3)

    # 4. Multi-Agent Interpretation & Theory Application
    pdf.chapter_title("4. Multi-Agent Interpretation & Theoretical Support")
    body4 = (
        "The Orchestrator (Agent 5) synthesizes outputs from the preceding agents. Rather than presenting isolated "
        "metrics, the report triangulates findings:\n\n"
        "A. Error-Correction (The Brain): The report highlights where the Reflective Loop corrected initial misclassifications "
        "(e.g., 'Agent 2 initially flagged Segment #45 as Assertive, but cross-referencing Agent 4\\'s collocation data "
        "triggered a self-correction to Indirect Directive').\n\n"
        "B. Episodic Memory Learning: The report notes how previous analyses informed current classifications, demonstrating "
        "adaptive learning rather than static NLP rules.\n\n"
        "C. Theoretical Grounding: Every claim is tethered to theory. For example, if a shift in formality is detected, "
        "it is explicitly justified using Halliday's Register Theory (Field, Tenor, Mode). If evasion is detected, it is "
        "proven using Grice's Maxim of Quantity violations. This ensures the output is peer-review ready for the research community."
    )
    pdf.chapter_body(body4)

    output_path = r"c:\Users\User\Desktop\PPPPPP\Research_Community_Report_Design.pdf"
    pdf.output(output_path)
    print(f"PDF generated successfully: {output_path}")

if __name__ == '__main__':
    generate_pdf()
